bot-token: ""
guild-name: "test"
discord-verify-command: '!verify'

presence:
  # 0 = default
  # 1 = streaming
  # 2 = listening
  # 3 = watching
  # 4 = custom status
  type: 4
  format: "%current%/%max% online"

# list of what ranks represent what roles, in the format 'rank:rolename'
ranks:
  - 'Lord:Lord/Lady'
  - 'Lady:Lord/Lady'
  - 'Champion:Champion'

# role to be removed when user verifies
discord-role-to-be-removed-on-verification: 'PendingVerification'

#MySQL connection info
MySQL:
  host: localhost
  port: 3306
  user: root
  database: minecraft
  password: ''

messages:
  not-eligible: "You were not eligible for any roles."